### ISSUE TITLE
UDP Packet Guide

### ISSUE THREAD

**Issue by winers1290** [snikch/escea#1]
You might find this protocol guide from Escea invaluable! See https://community.openhab.org/t/escea-gas-fire-binding-investigation/17896 for more info.

[Escea Fireplace LAN Comms Spec.pdf](https://github.com/snikch/escea/files/644165/630260_3.Escea.Fireplace.LAN.Comms.Spec.pdf)

**Comment by snikch** [comment]
This library has been updated based on this info 👍
