### ISSUE TITLE
Have you got a Home Assistant custom component for this code?

### ISSUE THREAD

**Issue by aheath70** [snikch/escea#2]
Hi Snikch

I am a user of Home Assistant, and I just got 2 x Escea heaters (DS1400 and DF700) installed in my house. I can control them with the Escea app, but I want to integrate them into HA.

I have no idea how to code a custom component. I have been through the documentation, and I think it is just a bridge too far to cross for me (I am an IT guy, but I work on the infrastructure side rather than the coding side). 

Have you ever thought of creating a custom component for this in HA?

**Comment by sads2000** [comment]
HA integration would be fantastic. I second this query. Cheers

**Comment by snikch** [comment]
HA custom component is available here: https://github.com/snikch/climate.escea
